functionsDirectory = "D:\\CODE\\SpaceDebris\\frontend\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\CODE\\SpaceDebris\\frontend\\build"
publishOrigin = "config"
commandOrigin = "config"
base = "D:\\CODE\\SpaceDebris\\frontend"
command = "npm run build"
functions = "D:\\CODE\\SpaceDebris\\frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]